Repository KB-technologia/FinMate_FE, pull requests merged in 2025-08, with the labels that each got.

#90 ♻️ 이메일 인증 로딩 추가
  FinMate/src/components/auth/RegisterForm.vue
  FinMate/src/components/auth/SignUpTermsForm.vue
Labels: enhancement

#89 ✨ 카카오 신규 유저 정보 저장 및 설문 전송 로직 추가
  FinMate/src/api/auth/auth.js
  FinMate/src/assets/signupSurvey.json
  FinMate/src/components/auth/SurveyComponent.vue
  FinMate/src/router/index.js
  FinMate/src/stores/auth/auth.js
  FinMate/src/stores/signup/signupStore.js
  FinMate/src/views/auth/KakaoRedirect.vue
  FinMate/src/views/auth/SignUpSurvey.vue
  FinMate/src/views/auth/SignupComplete.vue
Labels: bug, enhancement

#95 ♻️ 재무 포트폴리오 리팩토링 및 기능 구현
  FinMate/package.json
  FinMate/src/api/portfolio/portfolio.js
  FinMate/src/components/info/portfolio/ChooseDate.vue
  FinMate/src/components/info/portfolio/PortfolioAnalyzeChart.vue
  FinMate/src/components/info/portfolio/PortfolioCompareModal.vue
  FinMate/src/components/info/portfolio/PortfolioData.vue
  FinMate/src/components/info/portfolio/PortfolioEmpty.vue
  FinMate/src/components/info/portfolio/PortfolioModal.vue
  FinMate/src/components/info/portfolio/PortfolioPastChart.vue
  FinMate/src/styles/colors.css
  FinMate/src/views/info/MyPortfolioView.vue
Labels: enhancement

#98 ✨ 상품 리뷰 백엔드 api 연결 및 리뷰 모달 수정
  FinMate/src/api/product/productService.js
  FinMate/src/components/allshared/star/StarRating.vue
  FinMate/src/components/product/ProductCard.vue
  FinMate/src/components/review/WriteReviewModal.vue
  FinMate/src/views/product/AllProductView.vue
  FinMate/src/views/product/DetailProductView.vue
Labels: enhancement

#99 ✨ 마이페이지 - 캐릭터 다시 뽑기 모달 구현
  FinMate/src/api/info/userInfoAPI.js
  FinMate/src/assets/images/animals/Gacha_egg/egg_beige.png
  FinMate/src/assets/images/animals/Gacha_egg/egg_blue.png
  FinMate/src/assets/images/animals/Gacha_egg/egg_green.png
  FinMate/src/assets/images/animals/Gacha_egg/egg_pink.png
  FinMate/src/assets/images/animals/Gacha_egg/egg_purple.png
  FinMate/src/assets/images/etc/sea_background.png
  FinMate/src/assets/images/etc/speech.svg
  FinMate/src/assets/images/icons/arrow_triangle.svg
  FinMate/src/assets/images/logos/kiwi-family.png
  FinMate/src/assets/images/logos/kiwi-family2.svg
  FinMate/src/components/info/gacha/CharacterGachaBaseModal.vue
  FinMate/src/components/info/gacha/CharacterGachaDrawModal.vue
  FinMate/src/components/info/gacha/CharacterGachaIntroModal.vue
  FinMate/src/components/info/gacha/CharacterGachaModal.vue
  FinMate/src/components/info/gacha/CharacterGachaResultStep.vue
  FinMate/src/components/info/gacha/CharacterGachaWelcomeModal.vue
  FinMate/src/components/info/gacha/GachaDrawStep.vue
  FinMate/src/router/index.js
  FinMate/src/styles/colors.css
  FinMate/src/views/info/GachaTestView.vue
Labels: enhancement

#102 ♻️ api 통합 수정
  FinMate/src/api/dailyquiz/dailyQuiz.js
  FinMate/src/api/info/userInfoAPI.js
  FinMate/src/api/main/api.js
  FinMate/src/api/portfolio/portfolio.js
  FinMate/src/api/product/productService.js
Labels: bug

#105 🐛일반로그인 수정
  FinMate/package-lock.json
  FinMate/src/stores/auth/auth.js
Labels: bug

#108 ✨ 메인 페이지 스탯 부분 개발 및 테스트 api toast 처리
  FinMate/src/api/main/main.js
  FinMate/src/components/main/ShowStatsContainer.vue
  FinMate/src/components/quiz/QuizComponent.vue
  FinMate/src/styles/checkbox.scss
  FinMate/src/views/info/MyPortfolioView.vue
Labels: enhancement

#107 ✨ 아이디 찾기 페이지 개발
  FinMate/src/api/auth/auth.js
  FinMate/src/components/auth/FindId.vue
  FinMate/src/components/auth/RegisterForm.vue
  FinMate/src/views/auth/FindIdView.vue
  package-lock.json
Labels: enhancement

#112 ✨ 마이페이지 - 사용자 리뷰 조회 API 연동
  FinMate/src/api/info/userReviewAPI.js
  FinMate/src/components/review/ReviewCard.vue
  FinMate/src/router/index.js
  FinMate/src/views/info/MyReviews.vue
Labels: enhancement

#116 💄 회원가입 완료 페이지 수정
  FinMate/src/components/auth/LoginForm.vue
  FinMate/src/router/index.js
  FinMate/src/views/auth/LoginView.vue
  FinMate/src/views/auth/SignupComplete.vue
Labels: enhancement

#122 🐞 펀드 상품 상세 페이지 텍스트 UI 오류 현상 수정
  FinMate/src/components/allshared/star/StarRating.vue
  FinMate/src/components/allshared/star/StarRatingWithDetail.vue
  FinMate/src/components/product/ProductDetailCardFund.vue
  FinMate/src/components/review/ReviewFilterBar.vue
  FinMate/src/components/review/WriteReviewModal.vue
  FinMate/src/views/product/DetailProductView.vue
Labels: bug, duplicate

#129 ✨ 즐겨찾기 API 연동 및 즐겨찾기 페이지 구현
  FinMate/src/api/product/productService.js
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/product/FavoriteProductCard.vue
  FinMate/src/components/product/ProductDetailCardDeposit.vue
  FinMate/src/components/product/ProductDetailCardFund.vue
  FinMate/src/components/product/ProductDetailCardSavings.vue
  FinMate/src/router/index.js
  FinMate/src/views/product/DetailProductView.vue
  FinMate/src/views/product/FavoritesView.vue
Labels: enhancement

#135 ♻️ 프론트 수정 1차
  FinMate/src/assets/images/icons/LogoutRounded.png
  FinMate/src/assets/images/logos/kiwiLogo4.png
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/ProfileContainer.vue
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/components/main/ShowStatsContainer.vue
  FinMate/src/components/quiz/QuizComponent.vue
  FinMate/src/styles/colors.css
  FinMate/src/views/product/AllProductView.vue
  FinMate/src/views/product/FavoritesView.vue
  FinMate/src/views/quiz/QuizStartView.vue
Labels: bug

#136 ✨ STAT 성향 (가치관, 속도 등) 항목 아이콘 UI 개선
  FinMate/src/assets/images/icons/ticket.png
  FinMate/src/components/allshared/ConfirmModal.vue
  FinMate/src/components/allshared/Tooltip.vue
  FinMate/src/components/allshared/UserStatBar.vue
  FinMate/src/components/info/RightPanel.vue
  FinMate/src/components/info/UserStatsPanel.vue
  FinMate/src/components/info/gacha/CharacterGachaBaseModal.vue
  FinMate/src/components/info/gacha/CharacterGachaDrawModal.vue
  FinMate/src/components/info/gacha/CharacterGachaModal.vue
  FinMate/src/components/info/gacha/CharacterGachaResultStep.vue
  FinMate/src/components/info/stats/BarStatCard.vue
  FinMate/src/components/info/stats/ChoiceStatCard.vue
  FinMate/src/components/info/stats/UserStatsPanel.vue
  FinMate/src/components/info/stats/styles/stat-card.css
  FinMate/src/constants/userStatDescriptions.js
  FinMate/src/router/index.js
  FinMate/src/styles/colors.css
  FinMate/src/views/info/GachaTestView.vue
  FinMate/src/views/info/MyStatsView.vue
Labels: duplicate, enhancement

#145 💄 회원가입 설문 페이지 css 수정
  FinMate/src/assets/quiz.json
  FinMate/src/assets/signupSurvey.json
  FinMate/src/components/auth/SurveyComponent.vue
  FinMate/src/components/quiz/QuizComponent.vue
  FinMate/src/router/index.js
  FinMate/src/styles/reset.css
  FinMate/src/views/auth/SignUpSurvey.vue
Labels: enhancement

#144 ✨ 펀드 위험 토스트 메세지
  FinMate/src/components/allshared/Toast.vue
  FinMate/src/components/auth/SignUpTermsForm.vue
  FinMate/src/styles/colors.css
Labels: enhancement

#147 ✨마이페이지 레벨, 형용사, 티켓, 캐릭터 이미지 연동
  FinMate/src/api/mypage/character.js
  FinMate/src/api/mypage/level.js
  FinMate/src/components/info/stats/UserStatsPanel.vue
  FinMate/src/components/main/ShowStatsContainer.vue
Labels: enhancement

#157 ✨보유 상품 마이데이터 연동
  FinMate/src/api/info/userReviewAPI.js
  FinMate/src/components/info/UserProductCard.vue
  FinMate/src/views/info/MyProducts.vue
Labels: enhancement

#160 ✨ 메인페이지 추천상품 UI 디자인 변경
  FinMate/src/assets/images/etc/트럭2.png
  FinMate/src/assets/images/etc/화분.png
  FinMate/src/assets/images/etc/흙흙.png
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/components/product/ProductContainer.vue
Labels: enhancement

#166 🐛 출석 체크 계속 가능한 버그 해결
  FinMate/src/components/allshared/AttendanceCheckModal.vue
  FinMate/src/components/main/ProfileContainer.vue
Labels: bug

#168 🐛 메인 페이지 추천 상품 컨테이너 로그인 && 상품 추천 불가 할 때 상태 처리
  FinMate/src/api/main/main.js
  FinMate/src/assets/images/etc/flying.png
  FinMate/src/components/main/RandomProductContainer.vue
Labels: bug

#169 ♻️ 비교 모달 항목 수정 및 은행 로고 오류들 수정
  FinMate/src/api/product/productService.js
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/product/CompareButton.vue
  FinMate/src/components/product/FavoriteProductCard.vue
  FinMate/src/components/product/ProductCard.vue
  FinMate/src/components/product/ProductCompareModal.vue
  FinMate/src/components/product/ProductDetailCardDeposit.vue
  FinMate/src/components/product/ProductDetailCardFund.vue
  FinMate/src/components/product/ProductDetailCardSavings.vue
  FinMate/src/views/product/FavoritesView.vue
Labels: bug

#173 ♻️ 위험등급별 토스트 메세지
  FinMate/package.json
  FinMate/src/components/allshared/Toast.vue
  FinMate/src/styles/colors.css
  FinMate/src/views/product/AllProductView.vue
  FinMate/src/views/product/DetailProductView.vue
Labels: enhancement

#170 ✨ 전체 상품 페이지 디자인 변경
  FinMate/src/assets/images/etc/background.png
  FinMate/src/assets/images/etc/chick!.png
  FinMate/src/assets/images/etc/chick.png
  FinMate/src/assets/images/etc/frog!.png
  FinMate/src/assets/images/etc/frog.png
  FinMate/src/assets/images/etc/pot.png
  FinMate/src/assets/images/etc/rabbit!.png
  FinMate/src/assets/images/etc/rabbit.png
  FinMate/src/assets/images/etc/soil.png
  FinMate/src/assets/images/etc/truck.png
  FinMate/src/assets/images/etc/화분.png
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/components/product/ProductCard.vue
  FinMate/src/components/product/ProductContainer.vue
  FinMate/src/components/product/SearchByCondition.vue
Labels: enhancement

#171 ♻️ 마이페이지 포트폴리오 카드, 버튼 스타일 수정
  FinMate/src/components/info/portfolio/PortfolioData.vue
Labels: enhancement

#178 🔥 중복 코드 삭제
  FinMate/src/components/main/ProfileContainer.vue
Labels: bug

#182 🐛 버전 통일 관리 및 잔 버그 수정
  FinMate/.nvmrc
  FinMate/package-lock.json
  FinMate/src/api/mypage/level.js
  FinMate/src/components/main/RandomProductContainer.vue
  package-lock.json
Labels: bug, enhancement

#181 ✨ 메인 페이지 추천 상품 카드 padding 적용
  FinMate/src/components/main/MainProductCard.vue
Labels: enhancement

#183 ✨ 릴리즈: v1.0.0 – develop → main
  FinMate/.nvmrc
  FinMate/package-lock.json
  FinMate/package.json
  FinMate/src/api/mypage/level.js
  FinMate/src/assets/images/backgroundImage/quiz-bg.png
  FinMate/src/assets/images/logos/correctkiwi.png
  FinMate/src/assets/images/logos/kiwi-intro-quiz.png
  FinMate/src/assets/images/logos/kiwi-quiz.png
  FinMate/src/assets/images/logos/wrongkiwi.png
  FinMate/src/components/allshared/Toast.vue
  FinMate/src/components/dailyquiz/CorrectAnswerModal.vue
  FinMate/src/components/dailyquiz/DailyQuizModal.vue
  FinMate/src/components/dailyquiz/FalseButton.vue
  FinMate/src/components/dailyquiz/TrueButton.vue
  FinMate/src/components/dailyquiz/WrongAnswerModal.vue
  FinMate/src/components/dailyquiz/effects/ConfettiRain.vue
  FinMate/src/components/dailyquiz/modals/DailyQuizModal.vue
  FinMate/src/components/dailyquiz/modals/QuizDailyLimitModal.vue
  FinMate/src/components/dailyquiz/modals/QuizRewardIntroModal.vue
  FinMate/src/components/dailyquiz/modals/TalkResultModal.vue
  FinMate/src/components/dailyquiz/shared/FloatingChoiceButtons.vue
  FinMate/src/components/dailyquiz/shared/ModalMascot.vue
  FinMate/src/components/dailyquiz/shared/SpeechBubble.vue
  FinMate/src/components/dailyquiz/shared/TalkModalShell.vue
  FinMate/src/components/dailyquiz/shared/TypewriterText.vue
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/ProfileContainer.vue
  FinMate/src/components/main/RandomProductContainer.vue
  package-lock.json
Labels: documentation, enhancement

#185 ✨ 메인페이지- 추천상품보러가기 버튼 위치 변경
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/styles/colors.css
Labels: enhancement

#187 ✨ 로그인/회원가입 페이지 Enter 키 제출 지원
  FinMate/src/components/allshared/ConfirmModal.vue
  FinMate/src/components/auth/FindId.vue
  FinMate/src/components/auth/LoginForm.vue
  FinMate/src/components/auth/RegisterForm.vue
  FinMate/src/components/info/Sidebar.vue
  FinMate/src/components/info/stats/ChoiceStatCard.vue
  FinMate/src/components/info/stats/UserStatsPanel.vue
Labels: enhancement

#191 ✨ 상품 상세보기 컨트롤러 추가
  FinMate/src/components/product/ProductDetailCardDeposit.vue
  FinMate/src/components/product/ProductDetailCardFund.vue
  FinMate/src/components/product/ProductDetailController.vue
  FinMate/src/components/product/ProductRateChart.vue
  FinMate/src/views/product/DetailProductView.vue
Labels: documentation, enhancement

#196 ✨ AI 분석에 캐릭터 이미지 추가
  FinMate/package-lock.json
  FinMate/src/api/product/productService.js
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/product/CompareButton.vue
  FinMate/src/components/product/FavoriteProductCard.vue
  FinMate/src/components/product/ProductCard.vue
  FinMate/src/components/product/ProductCompareModal.vue
  FinMate/src/components/product/ProductDetailCardDeposit.vue
  FinMate/src/components/product/ProductDetailCardFund.vue
  FinMate/src/components/product/ProductDetailCardSavings.vue
  FinMate/src/components/product/SearchByCondition.vue
  FinMate/src/utils/bank.js
  FinMate/src/views/product/DetailProductView.vue
  FinMate/src/views/product/FavoritesView.vue
Labels: enhancement
