Repository KB-technologia/FinMate_FE, pull requests merged in 2025-07, with the labels that each got.

#4 ✨ MainPage 비로그인 파트 구현
  FinMate/package-lock.json
  FinMate/package.json
  FinMate/src/App.vue
  FinMate/src/api/main/main.js
  FinMate/src/assets/fonts/TMONBlack.ttf
  FinMate/src/assets/fonts/font.css
  FinMate/src/assets/images/capybara.png
  FinMate/src/assets/images/cat.png
  FinMate/src/assets/images/desertfox.png
  FinMate/src/assets/images/flyingsquirrel.png
  FinMate/src/assets/images/kiwiLogo.png
  FinMate/src/assets/images/kiwiLogo_Footer.png
  FinMate/src/assets/images/kiwibird.png
  FinMate/src/assets/images/koala.png
  FinMate/src/assets/images/panda.png
  FinMate/src/assets/images/penguin.png
  FinMate/src/assets/images/redpanda.png
  FinMate/src/assets/images/seaotter.png
  FinMate/src/components/allshared/FooterComponent.vue
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/ProfileContainer.vue
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/components/main/RealTimeInfoBar.vue
  FinMate/src/components/main/ShowStatsContainer.vue
  FinMate/src/style.css
  FinMate/src/views/main/MainView.vue
  FinMate/vite.config.js
Labels: enhancement

#6 📝 docs: add frontend README
  README.md
Labels: documentation

#7 ✨ MainPage 로그인 파트 구현 및 로그인 페이지 구현
  FinMate/index.html
  FinMate/package-lock.json
  FinMate/package.json
  FinMate/src/api/auth/auth.js
  FinMate/src/assets/images/LogoutRounded.png
  FinMate/src/components/allshared/FooterComponent.vue
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/auth/LoginForm.vue
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/ProfileContainer.vue
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/components/main/RealTimeInfoBar.vue
  FinMate/src/components/main/ShowStatsContainer.vue
  FinMate/src/main.js
  FinMate/src/stores/auth/auth.js
  FinMate/src/views/auth/LoginView.vue
  FinMate/src/views/main/MainView.vue
Labels: enhancement

#10 ✨ 마이페이지 공통 컴포넌트 구현
  FinMate/src/assets/fonts/font.css
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/info/RightPanel.vue
  FinMate/src/components/info/Sidebar.vue
  FinMate/src/main.js
  FinMate/src/styles/colors.css
  FinMate/src/styles/fonts.css
  FinMate/src/views/info/MyInfoView.vue
Labels: enhancement

#15 ✨ 마이페이지 회원 정보 수정 페이지 구현
  FinMate/src/components/info/UserInfoForm.vue
  FinMate/src/styles/colors.css
  FinMate/src/views/info/MyInfoView.vue
Labels: enhancement

#17 ✨ 출석 체크 모달 및 전역 스타일 적용 완료
  FinMate/src/api/auth/auth.js
  FinMate/src/assets/images/speech.png
  FinMate/src/assets/images/stamp-off.png
  FinMate/src/assets/images/stamp-on.png
  FinMate/src/components/allshared/AttendanceCheckModal.vue
  FinMate/src/components/allshared/FooterComponent.vue
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/auth/LoginForm.vue
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/ProfileContainer.vue
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/components/main/RealTimeInfoBar.vue
  FinMate/src/components/main/ShowStatsContainer.vue
  FinMate/src/stores/auth/auth.js
  FinMate/src/views/main/MainView.vue
Labels: enhancement

#19 ✨ 재무 포트폴리오 페이지 구현
  FinMate/src/views/info/MyPortfolioView.vue
  README.md
Labels: enhancement

#30 ✨ 투자 진단 테스트 페이지 완료
  FinMate/src/assets/images/kiwiLogo2.png
  FinMate/src/assets/quiz.json
  FinMate/src/components/allshared/FooterComponent.vue
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/quiz/QuizComponent.vue
  FinMate/src/router/index.js
  FinMate/src/views/quiz/Quiz0View.vue
  FinMate/src/views/quiz/Quiz1View.vue
  FinMate/src/views/quiz/Quiz2View.vue
  FinMate/src/views/quiz/Quiz3View.vue
  FinMate/src/views/quiz/Quiz4View.vue
  FinMate/src/views/quiz/Quiz5View.vue
  FinMate/src/views/quiz/Quiz6View.vue
  FinMate/src/views/quiz/Quiz7View.vue
  FinMate/src/views/quiz/QuizStartView.vue
  FinMate/src/views/quiz/QuizView.vue
Labels: enhancement

#31 ✨ 로그인 API 연동 및 실제 서버 통신 구현
  FinMate/src/api/auth/auth.js
Labels: enhancement

#29 ✨재무 포트폴리오 수정, 생성 모달 구현 및 컴포넌트 분리
  FinMate/package.json
  FinMate/src/api/portfolio/portfolio.js
  FinMate/src/assets/images/annualincome.png
  FinMate/src/assets/images/blurrychart.png
  FinMate/src/assets/images/editpencil.png
  FinMate/src/assets/images/infokiwi.png
  FinMate/src/assets/images/lock.png
  FinMate/src/assets/images/portfolioinfo.png
  FinMate/src/assets/images/totalassets.png
  FinMate/src/components/portfolio/PortfolioContainer.vue
  FinMate/src/components/portfolio/PortfolioModal.vue
  FinMate/src/views/info/MyPortfolioView.vue
Labels: enhancement

#37 ✨ 카카오 로그인 기능 프론트 구현 및 백엔드 연동
  FinMate/src/components/auth/LoginForm.vue
  FinMate/src/router/index.js
  FinMate/src/views/auth/KakaoRedirect.vue
Labels: duplicate, enhancement

#38 ✨ 전체 상품 페이지 개발
  FinMate/src/api/main/api.js
  FinMate/src/api/product/productService.js
  FinMate/src/assets/images/banks/bnk.png
  FinMate/src/assets/images/banks/hana.png
  FinMate/src/assets/images/banks/ibk.png
  FinMate/src/assets/images/banks/im.png
  FinMate/src/assets/images/banks/kakao.png
  FinMate/src/assets/images/banks/kb.png
  FinMate/src/assets/images/banks/kbank.png
  FinMate/src/assets/images/banks/nh.png
  FinMate/src/assets/images/banks/sc.png
  FinMate/src/assets/images/banks/shinhan.png
  FinMate/src/assets/images/banks/toss.png
  FinMate/src/assets/images/banks/woori.png
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/product/CompareButton.vue
  FinMate/src/components/product/Pagination.vue
  FinMate/src/components/product/ProductCard.vue
  FinMate/src/components/product/ProductContainer.vue
  FinMate/src/components/product/SearchByCondition.vue
  FinMate/src/router/index.js
  FinMate/src/views/product/AllProductView.vue
Labels: enhancement

#43 ♻️ 상품 정렬 기능 수정
  FinMate/src/components/allshared/Pagination.vue
  FinMate/src/components/allshared/Toast.vue
  FinMate/src/components/product/ProductContainer.vue
  FinMate/src/views/product/AllProductView.vue
Labels: duplicate, enhancement

#47 ♻️ 경험치 바 UI 추가 및 로직 수정
  FinMate/src/components/dailyquiz/CorrectAnswerModal.vue
  FinMate/src/components/dailyquiz/DailyQuizModal.vue
  FinMate/src/components/dailyquiz/WrongAnswerModal.vue
Labels: enhancement

#49 ✨ 카카오 로그인 router 추가
  FinMate/src/router/index.js
Labels: enhancement

#51 ♻️ daily_quiz api 수정
  FinMate/src/api/dailyquiz/dailyQuiz.js
  FinMate/src/api/portfolio/portfolio.js
  FinMate/src/components/dailyquiz/DailyQuizModal.vue
Labels: bug

#54 ✨ 상품 상세 페이지 구현
  FinMate/src/App.vue
  FinMate/src/components/allshared/Pagination.vue
  FinMate/src/components/allshared/Toast.vue
  FinMate/src/components/allshared/star/StarRating.vue
  FinMate/src/components/allshared/star/StarRatingWithDetail.vue
  FinMate/src/components/product/ProductDetailCardDeposit.vue
  FinMate/src/components/product/ProductDetailCardFund.vue
  FinMate/src/components/product/ProductDetailCardSavings.vue
  FinMate/src/components/review/RatingDetailModal.vue
  FinMate/src/components/review/ReviewCard.vue
  FinMate/src/components/review/ReviewFilterBar.vue
  FinMate/src/components/review/WriteReviewModal.vue
  FinMate/src/router/index.js
  FinMate/src/styles/colors.css
  FinMate/src/styles/reset.css
  FinMate/src/utils/bank.js
  FinMate/src/views/NotFoundView.vue
  FinMate/src/views/product/DetailProductView.vue
Labels: enhancement

#58 🐛 상품 상세 페이지 footer 부분 수정
  FinMate/src/components/review/ReviewCard.vue
  FinMate/src/views/product/DetailProductView.vue
Labels: documentation

#63 ♻️ CloseButton 컴포넌트 분리
  FinMate/src/components/allshared/CloseButton.vue
Labels: enhancement

#64 ✨ 마이페이지 - 사용자 리뷰 조회 기능 개발
  FinMate/src/components/info/Sidebar.vue
  FinMate/src/components/review/ReviewCard.vue
  FinMate/src/styles/colors.css
  FinMate/src/views/info/MyReviews.vue
Labels: enhancement

#68 💄 메인 페이지 각 컴포넌트 backgroundcolor 수정(1차)
  FinMate/src/components/allshared/FooterComponent.vue
  FinMate/src/components/allshared/TopNavigationBar.vue
  FinMate/src/components/info/UserStatsPanel.vue
  FinMate/src/components/main/MainProductCard.vue
  FinMate/src/components/main/ProfileContainer.vue
  FinMate/src/components/main/RandomProductContainer.vue
  FinMate/src/components/main/ShowStatsContainer.vue
  FinMate/src/styles/colors.css
  FinMate/src/views/main/MainView.vue
Labels: documentation

#75 ♻️ 금융 퀴즈 모달 디자인 수정 및 CloseButton 크기 수정
  FinMate/src/components/allshared/CloseButton.vue
  FinMate/src/components/dailyquiz/CorrectAnswerModal.vue
  FinMate/src/components/dailyquiz/DailyQuizModal.vue
  FinMate/src/components/dailyquiz/WrongAnswerModal.vue
  FinMate/src/styles/colors.css
Labels: enhancement

#79 ✨ 상품 비교 모달 개발
  FinMate/src/api/main/api.js
  FinMate/src/api/product/productService.js
  FinMate/src/components/allshared/Pagination.vue
  FinMate/src/components/product/CompareButton.vue
  FinMate/src/components/product/ProductCard.vue
  FinMate/src/components/product/ProductCompareModal.vue
  FinMate/src/components/product/ProductContainer.vue
  FinMate/src/views/product/AllProductView.vue
Labels: enhancement

#85 ✨ 마이페이지 - 회원 정보 수정 API 연동
  FinMate/src/api/info/userInfoAPI.js
  FinMate/src/assets/images/logos/flying-kiwi.png
  FinMate/src/assets/images/logos/kiwi-writing.png
  FinMate/src/assets/images/logos/paper-falling.png
  FinMate/src/components/allshared/LoadingOverlay.vue
  FinMate/src/components/info/RightPanel.vue
  FinMate/src/components/info/Sidebar.vue
  FinMate/src/components/info/UserInfoForm.vue
  FinMate/src/components/info/onClickEmailVerify.vue
  FinMate/src/styles/colors.css
  FinMate/src/views/info/MyInfoView.vue
Labels: enhancement
